---

# install
- name: Ensure role dependencies are installed.
  package:
    name:   "{{ item }}"
  with_items:
    - vsftpd
    - policycoreutils-python

# configure
- name: Touch deny user list file.
  copy: dest={{ vsftpd_chroot_list_file }} content="" mode=0640 force=no

- name: Edit user_list in order to login by the root user.
  lineinfile:
    dest: "{{ vsftpd_userlist_file }}"
    state: present
    regexp: 'root'
    line: '#root'
  when: vsftpd_allow_root_login

- name: Edit ftpusers in order to login by the root user.
  lineinfile:
    dest: /etc/vsftpd/ftpusers
    state: present
    regexp: 'root'
    line: '#root'
  when: vsftpd_allow_root_login

- name: Edit chroot_list allow to go up to the hierarchy of the top.
  lineinfile:
    dest: "{{ vsftpd_chroot_list_file }}"
    state: present
    regexp: 'root'
    line: 'root'
  when: vsftpd_allow_root_login

- name: "firewalld permits inbound FTP."
  firewalld:
    service:       "{{ item }}"
    permanent:  true
    state:      enabled
    immediate:  yes
  with_items:
    - ftp

- name: "Create directories that need to be writeable."
  file:
    path:   "{{ item }}"
    owner:  root
    group:  ftp
    mode:   0775
    setype: public_content_rw_t
    state:  directory
  with_items: "{{ vsftpd_writable_dirs }}"
  when: vsftpd_write_enable

- name: "Set SELinux context for vsftpd to write files."
  sefcontext:
    target:   "{{ item }}(/.*)?"
    setype:   public_content_rw_t
    state:    present
  with_items: "{{ vsftpd_writable_dirs }}"
  when: vsftpd_write_enable

- name: "Enable the SELinux Boolean: allow_ftpd_anon_write"
  seboolean:
    name:       allow_ftpd_anon_write
    state:      yes
    persistent: yes
  when: vsftpd_anon_upload_enable

- name: "Enable the SELinux Boolean: ftpd_use_passive_mode"
  seboolean:
    name:       ftpd_use_passive_mode
    state:      yes
    persistent: yes

- name: Place vsftpd configuration file in place.
  template: src=vsftpd.conf.j2 dest=/etc/vsftpd/vsftpd.conf
  notify: restart vsftpd

- name: Ensure vsftpd is started and enabled to start at boot.
  service: name=vsftpd state=started enabled=yes
